name: Module 108

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Task Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout repo with tests
        uses: actions/checkout@master
        with:
          repository: linerotechab/kotlin-hw-results
          token: ${{ secrets.my_pat }}
          path: ./kotlin-hw-results

      - name: Move helper files
        run: cp -r ./kotlin-hw-results/src/test/kotlin/helper ./src/test/kotlin

      - name: Move test files
        run: |
          cp -r ./kotlin-hw-results/src/test/kotlin/lms_135 ./src/test/kotlin
          gradle --version

      - name: Test LMS 135
        run: gradle test --tests "lms_135.*"